[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src
        'self'
        https://brkzboljsaylkzvygjnx.supabase.co
        wss://brkzboljsaylkzvygjnx.supabase.co
        https://cdn.jsdelivr.net
        https://unpkg.com
        https://lottie.host
        https://www.google-analytics.com
        https://analytics.google.com;
      script-src
        'self'
        'unsafe-inline'
        'unsafe-eval'
        https://www.googletagmanager.com
        https://www.google-analytics.com;
      img-src
        'self'
        https://brkzboljsaylkzvygjnx.supabase.co
        https://www.google-analytics.com
        data:
        blob:;
      worker-src 'self' blob:;
    """
